name:  Custom Action Docker
on: 
   
run-name: Custom Actions - Docker
jobs:
    Hello:
        runs-on: ubuntu-latest 
        outputs:
            time: ${{ steps.HelloToYou.outputs.time }}
        steps:     
            - name: Checkout
              uses: actions/checkout@v2 
            - name: HelloToYou
              id: HelloToYou
              uses: ./.github/actions/hello-to-you-docker   
              with:
                  name: 'Miguel' 
    #GetTheTime