name:  Custom Action Docker
on:  push
   
run-name: Custom Actions - Docker
jobs:
    Hello:
        runs-on: ubuntu-latest 
        outputs:
            time: ${{ steps.HelloToYou.outputs.time }}
        steps:     
            - name: Checkout
              uses: actions/checkout@v4

            - name: tree
              run: ls -l
            - name: HelloToYou
              id: HelloToYou
              uses: ./.github/actions/hello-to-you-docker   
              with:
                  name: 'Miguel' 
    #GetTheTime